## FILE CONTAINS ALL ONCLICK EVENTS

## TURNS FOG OF WAR ON FOR GAME
def fog_on():
    print("TOGGLED FOG OF WAR ON")
## TURNS FOG OF WAR OFF FOR GAME
def fog_off():
    print("TOGGLED FOG OF WAR OFF")